### PR TITLE
Rename conversion task slug from 'preanalysis' to 'analysis'

### PR DESCRIPTION
**Pull request by andywaltlova**
RHINENG-10825

Renames slug of conversion `preanalysis` task to `analysis`.

- [x] Severity maps, fixtures, warning constants renamed
- [x] Needs backend PR + IQE plugin

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.7.3) is older than required version (6.0.0)

**Comment by andywaltlova** [comment]
MR for advisor-backend !891 was merged, but I am not sure if db fixtures updated, or if that has to be done manually when we have this MR - to make it as smooth transition as we can.

hmm thinking about it I could probably make this MR backwards compatible so it can be merged anytime and it can work with both slugs, the old and new one :thinking:

**Review by r0x0d — APPROVED** [review]
Looks good from my point of view

**Comment by gkarat** [comment]
Hey, thanks for the PR @andywaltlova. I have tested it locally and I see that the quickstart button has returned for the pre-conversion task which is great. There are some linter issues though: please run `npm run lint` and `npm run test` and push the changes again to fix them.

**Pull request merged**
