### PR TITLE
Add release scripts

### PR DESCRIPTION
**Pull request by johnsonm325**
Add scripts for release to stage-stable, prod-beta and prod-stable.

### CODE REVIEW

**Comment by leSamo** [comment]
Can you please run `chmod u+x release-prod-stable release-prod-beta` in `scripts/` so the scripts are executable by default?

**Comment by leSamo** [comment]
Scripts look good, I'm still not sure about releasing to stage-stable directly from master, most of our apps don't do that.

**Comment by johnsonm325** [comment]
@leSamo That's fair. Tasks folks wanted everything in stage-stable, but I think that's mostly for testing for release. I think I can fix that and push again so we release directly to stage-beta instead.

**Review by leSamo — APPROVED** [review]
Looks good!

**Pull request merged**
