### PR TITLE
fix(SystemsTable): RHINENG-10561 - Fix OS filter conversion

### PR DESCRIPTION
**Pull request by bastilian**
This fixes issues converting the OS group filter value to the Tasks API operating_system filter. 

How to test:

 1) Open any page with systems and test filtering them (not only the OS filter)

### CODE REVIEW

**Review by gkarat — COMMENTED** [review]
The tables result in something went wrong still if you want to filter CentOS hosts. This is an example of the API request which is incorrect and results in 400:
```
/api/tasks/v1/task/ping/systems?limit=10&offset=0&sort=-last_seen&operating_system=RHEL|9.5,RHEL|9.4,RHEL|9.3,RHEL|9.2,RHEL|9.1,RHEL|9.0,CentOS|7,CentOS|7
```

**Comment by bastilian** [comment]
@gkarat Thank you for testing! That issue should now be fixed and it can handle all variations of OSes.

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.7.3) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (4.7.3) is older than required version (6.0.0)

**Review by gkarat — APPROVED** [review]
lgtm, thanks for all the edits. the table works fine for different tasks and it filters out needed systems by OS

**Pull request merged**
