### PR TITLE
Add severity mapping for conversion tasks

### PR DESCRIPTION
**Pull request by johnsonm325**
Test this on insights-qa account on /tasks/executed/6009. It will fail in stage but pass on this PR.

### CODE REVIEW

**Comment by mshriver** [comment]
```15:58:51 docker: Error response from daemon: Get "https://quay.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers).```

Going to have to wait for this to clear, the PR build failure isn't related to PR content.

**Comment by tpapaioa** [comment]
Verified in testing w/ local frontend that this resolves the error for /tasks/executed/6009

**Review by adonispuente — APPROVED** [review]
LGTM

**Pull request merged**
